sudo: false

notifications:
  email: false

language: scala

jdk: openjdk8

scala:
  - 2.12.10
  - 2.13.1

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - $HOME/.coursier/cache

before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

before_install:
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then bash
    scripts/decrypt-keys.sh; fi
  - export PATH=${PATH}:./vendor/bundle

install:
  - rvm use 2.6.0 --install --fuzzy
  - gem update --system
  - gem install sass
  - gem install jekyll -v 3.2.1

stages:
  - name: test
  - name: deploy
    if: branch = master AND type != pull_request

jobs:
  include:
    - stage: deploy
      script:
        - bash scripts/publishMicrosite.sh
    - stage: test
      script:
        - sbt ++$TRAVIS_SCALA_VERSION compile
        - ./scalafmt --test --non-interactive